## 00. Pytorch Fundamentals
Resources and References:
* Github Page: https://github.com/mrdbourke/pytorch-deep-learning
* Book version: https://www.learnpytorch.io
* YouTube: http://www.youtube.com/watch?v=V_xro1bcAuA
* [3blue1brown's Essence of linear algebra]()


In [1]:
import torch
# import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cpu


## Introduction to Tensors

Creating Tensors

Pyorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html


### Scalar

A scalar has no (zero) dimensions.

Its a single number

Named with lowercase


In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# To get Tensor back as python int we use .item()
scalar.item()

7

### Vector

A number with magnitude(size) and direction (eg. wind speed with direction) but can have many other numbers

It has 1 dimension

Dimensions -> No. of pairs of closing square brackets

Shape

Named with lowercase


In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

### MATRIX

A 2-dimensional array of numbers

Named with Uppercase


In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
print(
    f"Value at Index on zero'th axis: \n {MATRIX[0]}\nValue at index on first dimension: \n {MATRIX[1]}"
)

Value at Index on zero'th axis: 
 tensor([7, 8])
Value at index on first dimension: 
 tensor([ 9, 10])


In [12]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

An n-dimensional array of numbers.
can be any no.

Named with Uppercase


In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

For the tensor TENSOR of shape -> torch.size([1, 3, 3])

This means there's 1 dimension of 3 by 3

dim=0 the outside bracket lines up with (1)

dim=1 the middle bracket lines up with (3)

dim=2 the inner bracket lines up with (3)


In [16]:
# dim = 0
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Creating Random Tensors in Pytorch

### Why random tensors?

Neural nets learns by starting with tensors full of random numbers then adjust those random numbers to better represent the data

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html
(torch.rand)


In [17]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6540, 0.5621, 0.4263, 0.9757],
        [0.0549, 0.5366, 0.9981, 0.0759],
        [0.1060, 0.5681, 0.6028, 0.8843]])

In [18]:
# no. of dimensions of random_tensor
random_tensor.ndim

2

In [19]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, color channels(R, G, B)

print(f"Shape: {random_image_size_tensor.shape}\nndim: {random_image_size_tensor.ndim}")

Shape: torch.Size([224, 224, 3])
ndim: 3


## Creating Tensors with Zeros and Ones in PyTorch


In [20]:
# Creating a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Creating a tensor of all ones

ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
# data type
ones.dtype

torch.float32

### -> Creating tensors in a range and tensors-like


In [24]:
# Creating a range using torch.arange()

one_to_nine = torch.arange(0, 10)
one_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
zero_to_thousand = torch.arange(start=0, end=1000, step=77)
zero_to_thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### -> Dealing with Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

- Default datatype is `torch.float32` (1 precision)
- Default device is `cpu`


In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False
)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
# Float 16 tensor
float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0], dtype=torch.float16, device=None, requires_grad=False
)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [31]:
float_16_tensor2 = float_32_tensor.type(torch.float16)
float_16_tensor2

tensor([3., 6., 9.], dtype=torch.float16)

- Some tensor operations with different datatypes, will work some times but most of the time result in errors.


In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### -> Getting tensor attributes (information about tensors)

1. Tensor's datatype - `tensor.dtype`
2. Tensor's shape - `tensor.shape`
3. Tensor's device - `tensor.device`


In [35]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6970, 0.4412, 0.6589, 0.7323],
        [0.0986, 0.5292, 0.9261, 0.7214],
        [0.5724, 0.0330, 0.2224, 0.7828]])

In [36]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6970, 0.4412, 0.6589, 0.7323],
        [0.0986, 0.5292, 0.9261, 0.7214],
        [0.5724, 0.0330, 0.2224, 0.7828]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### -> Manipulating Tensors (Tensor Operations)

Tensor operations:

- Addition
- Subtraction
- Multiplication (element-wise)
- Duvision
- Matrix multiplicatin


In [37]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1, 2, 3])

tensor_plus_10 = tensor + 10
print(f"Original tensor:\n{tensor}")
print(f"Resulting tensor after adding 10:\n{tensor_plus_10}")

Original tensor:
tensor([1, 2, 3])
Resulting tensor after adding 10:
tensor([11, 12, 13])


In [38]:
# Multiply tensor by 10

tensor_times_10 = tensor * 10
print(f"Original tensor:\n{tensor}")
print(f"Resulting tensor after multiplying by 10:\n{tensor_times_10}")

Original tensor:
tensor([1, 2, 3])
Resulting tensor after multiplying by 10:
tensor([10, 20, 30])


In [39]:
# Subtract tensor by 10

tensor_minus_10 = tensor - 10
print(f"Original tensor:\n{tensor}")
print(f"Resulting tensor after subtructing 10:\n{tensor_minus_10}")

Original tensor:
tensor([1, 2, 3])
Resulting tensor after subtructing 10:
tensor([-9, -8, -7])


In [40]:
# Using PyTorch built-in functions
tensor_torch_mul_10 = torch.mul(tensor, 10)
print(f"Original tensor:\n{tensor}")
print(f"Resulting tensor after applying PyTorch mul by 10:\n{tensor_torch_mul_10}")

Original tensor:
tensor([1, 2, 3])
Resulting tensor after applying PyTorch mul by 10:
tensor([10, 20, 30])


### -> Matrix mutiplication (part 1)

Two main ways of performing multiplication:

1. Element-wise
2. Matrix multiplication (dot product)


In [41]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix multiplication
# %%time
tensor_matmul = torch.matmul(tensor, tensor)
print(f"Original tensor matmul:\n{tensor} * {tensor}")
print(f"Resulting tensor matrix multiplication:\n{tensor_matmul}")

Original tensor matmul:
tensor([1, 2, 3]) * tensor([1, 2, 3])
Resulting tensor matrix multiplication:
14


In [44]:
tensor

tensor([1, 2, 3])

In [45]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [47]:
# Matrix multiplication by hand, for loop
# %%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)


### -> Matrix multiplication (part 2: the two main rules of matrix multplication)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:

- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will

2. The resulting matrix has the shape of ht **outer dimensions**:

- `(2, 3) @ (3, 2)` -> `(2, 2)`
- `(3, 2) @ (2, 3)` -> `(3, 3)`

Some important links:

- https://mathisfun.com
- https://matrixmultiplication.xyz


### -> Matrix multiplication (part 3: dealing with tensor shape errors)

- To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
- A **transpose** switches the axes or dimensions of a given tensor


In [58]:
# Shapes for matrix mul
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [59]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [60]:
# We transpose tensor_B for the matrix mul to work (for inner dim to be same)
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(
    f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.shape}"
)
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dims must match")
print("Output:\n")

output = torch.mm(tensor_A, tensor_B.T)  # torch.mm == torch.matmul == '@' operator.
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([3, 2])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dims must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### -> Finding the min, max, mean and sum of tensors (Tensor Aggregation)


In [3]:
# Creating a tensor
tensor_x = torch.arange(start=0, end=100, step=10)
tensor_x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
# Finding the min
torch.min(tensor_x), tensor_x.min()


(tensor(0), tensor(0))

In [7]:
# Finding the max
torch.max(tensor_x), tensor_x.max()


(tensor(90), tensor(90))

In [11]:
tensor_x.dtype

torch.int64

In [12]:
# Mean -> does not work with Long(int64) dtype, can only work with either float32 or complex dtypes
torch.mean(tensor_x.type(torch.float32)), tensor_x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [14]:
# Sum
torch.sum(tensor_x), tensor_x.sum()


(tensor(450), tensor(450))

### -> Finding the positional min and max of tensors


In [15]:
tensor_x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
# Finding the position in tensor that has the minimum value with argmin() -> returns index position of target tensor value where the minimum value occurs
tensor_x.argmin()


tensor(0)

In [17]:
tensor_x[0]

tensor(0)

In [18]:
# Finding the position in tensor that has the maximum value with argmax()
tensor_x.argmax()


tensor(9)

In [19]:
tensor_x[9]

tensor(90)

### -> Reshaping, viewing, stacking, squeezing, unsqueezing and permuting tensors

- **Reshaping** - reshapes an input tensor to a defined shape
  - In _reshape_ the dimensions have to be _compatible with the original dimensions_.
- **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor (shows a tensor from a different perspective/shape)
- **Stacking** - combine multiple tensors on top of each other (vstack) or side by side (hstack)
  - Concatenates a sequence of tensors (of same size) along a new dimension
  - `torch.stack(tensors, dim=0, out=None) -> Tensor`, where _tensors_ is the sequence of tensors to concatenate, _dim(int)_ is what dimension to combine them on, and has btw 0 and the no. of dimensions of concatenated tensors. _out(Tensor, optional)_ is the output tensor.
  - There is also `torch.vstack` and `torch.hstack`.
- **Squeeze** - remove all `1` dimensions from a tensor.
- **Unsqueeze** - add a `1` dimension to a target tensor.
- **Permute** - Return a _view_ of the input with dimensions permuted _(swapped)_ in a certain way.

* The goal is to manipulate tensors in some way to change their shape or dimensions.


In [34]:
# Creating a tensor
tensor_y = torch.arange(1.0, 10.0)
tensor_y, tensor_y.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
# Add an extra dimension
tensor_y_reshaped = tensor_y.reshape(1, 9)
tensor_y_reshaped, tensor_y_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
tensor_y1_reshaped = tensor_y.reshape(9, 1)
tensor_y1_reshaped, tensor_y1_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [37]:
tensor_y, tensor_y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [38]:
# Change the view
z1 = tensor_y.view(9, 1)
z1, z1.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [39]:
# Change the view
z = tensor_y.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [40]:
# Changing z changes tensor_y (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, tensor_y


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [44]:
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
# Stack tensors on top of each other
y_stacked = torch.stack([z, z, z, z], dim=0)
y_stacked


tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [49]:
# Stacking, on dim 1
y1_stacked = torch.stack([z, z, z, z], dim=1)
y1_stacked


tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

### -> Squeezing, unsqueezing and permuting tensors

In [57]:
# torch.squeeze() -> removes all single dimensions from a target tensor
print(f"Initial tensor z: {z}")
print(f"Shape of initial tensor z: {z.shape}")

# Squeeze tensor z
z_squeezed = z.squeeze()
print(f"\nNew tensor: {z_squeezed}")
print(f"Shape of new (squeezed) tensor: {z_squeezed.shape}")

Initial tensor z: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape of initial tensor z: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Shape of new (squeezed) tensor: torch.Size([9])


In [58]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target (z_squeezed) tensor: {z_squeezed},\nShape: {z_squeezed.shape}")

# Add extra dimension with unsqueeze
z_unsqueezed = z_squeezed.unsqueeze(dim=0)
print(f"\nNew (unsqueezed) tensor: {z_unsqueezed}, \nshape: {z_unsqueezed.shape}")

Previous target (z_squeezed) tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
Shape: torch.Size([9])

New (unsqueezed) tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), 
shape: torch.Size([1, 9])


In [3]:
# torch.permute - rearranges the dimensons of a target tensor in a specified order (a view)
x_original = torch.rand(size=(224, 224, 3)) # h, w, c

# Permute the original tensor to rearrange the axis/dim order
x_permuted = x_original.permute(2, 0, 1) # shifts (changes view) into shape c, h, w

print(f"Previous shape: {x_original.shape}, \n(Heiht, Width, RGB color channels)")
print(f"\nNew (permuted shape): {x_permuted.shape}, \n(RGB color chanels, Height, Width)")

Previous shape: torch.Size([224, 224, 3]), 
(Heiht, Width, RGB color channels)

New (permuted shape): torch.Size([3, 224, 224]), 
(RGB color chanels, Height, Width)


### -> Selecting data from tensors (indexing)
Indexing with pyTorch is similar to indexing with NumPy

- You can also use `:` to select **all** of a target dimension
- **Slicing operations** can also be applied to tensors.

In [3]:
# Creatig a tensor
x = torch.arange(start=1, end=10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
# Indexing our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
# Index on the midde bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [8]:
x[0][1]

tensor([4, 5, 6])

In [9]:
x[0][2]

tensor([7, 8, 9])

In [10]:
x[0][0][0]

tensor(1)

In [11]:
x[0][0][1]

tensor(2)

In [12]:
x[0][2][2]

tensor(9)

In [13]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [14]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension (every middle[1] element of the innermost[:, :] bracket)
x[:, :, 1]

tensor([[2, 5, 8]])

In [19]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd diminsion
x[:, 1, 1]

tensor([5])

In [22]:
# Get all values of 0th dim, but index 1 elements[2nd dim] of 1st dimension  (in middle bracket, start from dim 1 to the rest/all following)
x[:, 1:, 1]

tensor([[5, 8]])

In [23]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [24]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [28]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

### -> PyTorch and NumPy
NumPy is a popular scientific Python numerical computing library. PyTorch has functionality to interact with it

* Convert data from NumPy arrays to PyTorch tensor -> `torch.from_numpy(ndarray)`.
* From PyTorch tensor to NumPy array -> `torch.Tensor.numpy()`

- NumPy default datatype if `float64`.
- PyTorch default datatype is `torch.float32`.

* **Warning**:
    - When converting from NumPy to PyTorch, PyTorch reflects NumPy's default datatype of  `float64` unless specified otherwise.
    - Same goes for PyTorch to Numpy, PyTorch tensor default datatype of `torch.float32` is reflected onto the numpy array.

In [31]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [35]:
print(f"NumPy array's datatype: {array.dtype}")

NumPy array's datatype: float64


In [36]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [37]:
# Tensor to NumPy array
pytorch_tensor = torch.ones(7)
numpy_array = pytorch_tensor.numpy()

pytorch_tensor, pytorch_tensor.dtype, numpy_array, numpy_array.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [38]:
# Change the tensor, what happens to `numpy_array`?
pytorch_tensor = pytorch_tensor + 1
pytorch_tensor, numpy_array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### -> PyTorch reproducibility (taking the random out of random)

To reduce the randomness in neural networks, PyTorch comes with the concept of a **random seed**

Esentially what the random seed does is "flavour" the randomness.

Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [39]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3666, 0.2320, 0.9830, 0.8959],
        [0.7942, 0.1805, 0.1571, 0.1199],
        [0.4936, 0.3117, 0.1440, 0.4212]])
tensor([[0.2494, 0.8921, 0.2358, 0.8228],
        [0.3204, 0.1929, 0.5590, 0.7827],
        [0.6194, 0.0808, 0.2565, 0.6006]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [41]:
# Set the random seed
RANDOM_SEED = 42

# torch.manual_seed(RANDOM_SEED) only works for one block of code, so it has to be repeated each time torch.rand() is called.
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### -> Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers thanks to CUDA + PyTorch working behind the scenes to make everything good(optimized to run fast)

#### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use Kaggle - Kaggle Notebooks
3. Use your own GPU - takes a little bit of setup and requires purchasing one.
    - There's a lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/03/which-gpu-for-deep-learning/
4. Use cloud computing - GCP, AWS, Azure (and alot of other providers now with the AI boom). These services allow you to rent compute.


For option 3 and 4, PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch documentation: https://pytorch.org/get-started/locally/

For option 1 (Google Colab), change runtime to GPU, to be allocated a GPU.

In [ ]:
# To check the allocated GPU
# nvidia-smi

#### 2. Check for GPU access with PyTorch

In [3]:
# 2. Check for GPU access with PyTorch
torch.cuda.is_available()

False

For PyTorch since its capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available else CPU

In [2]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [3]:
# Count the number of devices (Nvidia GPUs)
torch.cuda.device_count()

0

### -> Setting up device agnostic code and putting tensors on and of GPU

continuation...
#### -> Putting tensors (and models) on the CPU

We'll want our tensors/model on the GPU since computations are faster there.

In [5]:
# Create a tensor(default on the CPU)
tensor_cpu = torch.tensor([1, 2, 3])

print(tensor_cpu, tensor_cpu.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor_cpu.to(device)
tensor_on_gpu

tensor([1, 2, 3])

#### -> Moving tensors back to the CPU

- (on the device issues): **Converting tensors to numpy with `tensor.numpy()`** doesn't work with the GPU, **NumPy only works with CPU**. 
- Instead we use `tensor.cpu()` which will bring our target tensor back to CPU, and then we should be able to use it with NumPy.
- For Instance if we run `tensor_on_gpu.numpy`, we'll get a type error. (*Only if its on GPU*)

In [8]:
# If tensor is on GPU, can't ransform it to NumPy, error if device = GPU
# tensor_on_gpu.numpy()

In [9]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [10]:
tensor_on_gpu

tensor([1, 2, 3])

### 32. PyTorch Fundmentals exercises and extra-curriculum

visit https://www.learnpytorch.io/00_pytorch_fundamentals/#extra-curriculum

Github Page: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb
